openapi: 3.0.0
info:
  title: Node Express Postgres Auth Apis
  description: Cookie base authentication
  version: 1.0
  contact:
    email: surajit94malik@gmail.com
  lisence:
    name: Test
    url: test.com
servers:
  - url: http://localhost:3000
    description: This is the local server
  - url: https://example.api.com
    description: Production endpoint

paths:
#Login
  /auth/login:
    post:
      summary: Login
      description: Login providing username and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      reponses:
        200:
          description: Login succcesfull

